"""initial schema

Revision ID: 8907816f55ab
Revises:
Create Date: 2026-09-25 13:35:26.744622

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8907816f55ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('days_survived', sa.Integer(), nullable=False),
    sa.Column('final_sla_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('final_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('prestige_earned', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sla_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tech_debt', sa.Integer(), nullable=False),
    sa.Column('user_happiness', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=False),
    sa.Column('prestige_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitigation_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tech_debt_delta', sa.Integer(), nullable=False),
    sa.Column('resolve_speed_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('cooldown_ticks', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('achievement_key', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('compliance_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dilemma_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('dilemma_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('offered_at_tick', sa.Integer(), nullable=False),
    sa.Column('expires_at_tick', sa.Integer(), nullable=False),
    sa.Column('resolved_at_tick', sa.Integer(), nullable=True),
    sa.Column('resolved_choice_id', sa.String(length=50), nullable=True),
    sa.Column('was_auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.String(length=30), nullable=False),
    sa.Column('grid_x', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('grid_y', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchased_upgrades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('upgrade_id', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('purchased_at_tick', sa.Integer(), nullable=False),
    sa.Column('cost_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('dependencies_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unlocked_cosmetics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('cosmetic_id', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engineers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('assigned_service_id', sa.String(length=36), nullable=True),
    sa.Column('core_competency', sa.String(length=20), nullable=False),
    sa.Column('stress_level', sa.Integer(), nullable=False),
    sa.Column('stamina', sa.Integer(), nullable=False),
    sa.Column('on_call_status', sa.String(length=20), nullable=False),
    sa.Column('hired_at_tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('mtta_seconds', sa.Integer(), nullable=False),
    sa.Column('mttr_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_tick', sa.Integer(), nullable=False),
    sa.Column('acknowledged_tick', sa.Integer(), nullable=True),
    sa.Column('resolved_tick', sa.Integer(), nullable=True),
    sa.Column('triage_solved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    op.drop_table('engineers')
    op.drop_table('unlocked_cosmetics')
    op.drop_table('services')
    op.drop_table('purchased_upgrades')
    op.drop_table('infrastructure_nodes')
    op.drop_table('dilemma_events')
    op.drop_table('audit_logs')
    op.drop_table('achievements')
    op.drop_table('mitigation_actions')
    op.drop_table('game_sessions')
    op.drop_table('career_records')
    # ### end Alembic commands ###
